apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  DB_URL: amRiYzpteXNxbDovL2Vrcy1yZHMuY3RrbTgwODhvaXEzLmFwLW5vcnRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29tL29saXZlc2FmZXR5
  DB_PASSWORD: b2xpdmVzYWZldHk=
  JWT_TOKEN_SECRET: ZGU2OWM3YzI1YjJmZjU4NmYyMDYwODM5ZjEyZGI1M2ZjMzEwNWMwZDk5NTc1OGIxZTNiYzBmOGYzZDI2ZTYxN2MyMDczNWVlZWEzOTI0MWJiNGIyMDQ1OWRlN2RlYmNmOTNmMjBkNjcwMTVlYWQzYWIxZTQ1ZGNjNjEzZmJlNjg=
  REDIS_HOST: cmVkaXMtMTM5MjQuYzMyMS51cy1lYXN0LTEtMi5lYzIuY2xvdWQucmVkaXNsYWJzLmNvbQ==
  REDIS_PASSWORD: RzdYaEZHcldSSmJpVGlpanVPRmpIdGRidkJ4VlNIN00=
  REDIS_PORT: MTM5MjQ=

