spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      max-lifetime: 1800000
      idle-timeout: 300000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
      # show_sql: true
      format_sql: true
  logging:
    level:
      org.hibernate.SQL: info
      org.hibernate.type: info
  servlet:
    multipart:
      enabled: true
      maxFileSize: 1000MB
      maxRequestSize: 1000MB


cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    sns:
      topic:
        arn: ${AWS_SNS_ARN}
    sqs:
      queueUrl: ${AWS_SQS_URL}



jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}


